In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.optimize import linprog
from scipy.optimize import minimize

In [49]:
def object_MVO(w):
    #new_cov = cov
    zigma = np.sqrt(w.dot(cov).dot(w.T))
    return -(w.dot(u))/zigma

def object_Maximum_Diversification(w):
    #new_cov = cov
    zigma = np.sqrt(w.dot(cov).dot(w.T))
    return -(w.dot(zigma_v))/zigma

def object_Minimum_Variance(w):
    #new_cov = cov
    return w.dot(cov).dot(w.T)
             

##目標函數
def object_Equal_Risk(w):
    #new_cov = cov
    zigma = np.sqrt(w.dot(cov).dot(w.T))
    return ((w - zigma**2/cov.dot(w)/len(w))**2).sum()             
             
##限制條件
def constraint_EWRP(w):
    return 0.10 - np.sqrt(w.T.dot(cov).dot(w))*np.sqrt(252)
def constraint_equal_weight(w):
    return np.sum(w) - 1

In [10]:
w_int = np.array([1/3,1/3,1/3])

In [4]:
bound=[(0,1) for i in range(3)]

# 都一樣

In [16]:
u = [0.05,0.05,0.05]
zigma_v = [0.1,0.1,0.1]
cov = np.array([[0.01,0.001,0.001],[0.001,0.01,0.001],[0.001,0.001,0.01]])

In [20]:
minimize(object_MVO,w_int,method='SLSQP',\
                   bounds=bound, constraints={'type': 'eq', 'fun': constraint_equal_weight}).x

array([0.33333333, 0.33333333, 0.33333333])

In [21]:
minimize(object_Minimum_Diversification,w_int,method='SLSQP',\
                   bounds=bound, constraints={'type': 'eq', 'fun': constraint_equal_weight}).x

array([0.33333333, 0.33333333, 0.33333333])

In [15]:
minimize(object_Equal_Risk,w_int,method='SLSQP',\
                   bounds=bound, constraints={'type': 'eq', 'fun': constraint_equal_weight}).x

array([0.33333333, 0.33333333, 0.33333333])

In [25]:
u = [0.05,0.1,0.15]
zigma_v = [0.1,0.2,0.3]
cov = np.array([[0.01,0.002,0.003],[0.002,0.04,0.006],[0.003,0.006,0.09]])

In [26]:
cov

array([[0.01 , 0.002, 0.003],
       [0.002, 0.04 , 0.006],
       [0.003, 0.006, 0.09 ]])

In [32]:
minimize(object_MVO,w_int,method='SLSQP',\
                   bounds=bound, constraints={'type': 'eq', 'fun': constraint_equal_weight}).x

array([0.54541786, 0.27278494, 0.1817972 ])

In [28]:
minimize(object_Minimum_Diversification,w_int,method='SLSQP',\
                   bounds=bound, constraints={'type': 'eq', 'fun': constraint_equal_weight}).x

array([0.5453525 , 0.27289106, 0.18175645])

In [29]:
minimize(object_Equal_Risk,w_int,method='SLSQP',\
                   bounds=bound, constraints={'type': 'eq', 'fun': constraint_equal_weight}).x

array([0.54547555, 0.27277189, 0.18175256])

In [37]:
u = [0.05,0.1,0.15]
zigma_v = [0.1,0.2,0.3]
cov = np.array([[0.01,0.004,0.006],[0.004,0.04,0.03],[0.006,0.03,0.09]])

In [38]:
cov

array([[0.01 , 0.004, 0.006],
       [0.004, 0.04 , 0.03 ],
       [0.006, 0.03 , 0.09 ]])

In [39]:
minimize(object_MVO,w_int,method='SLSQP',\
                   bounds=bound, constraints={'type': 'eq', 'fun': constraint_equal_weight}).x

array([0.62211422, 0.22697901, 0.15090677])

In [40]:
minimize(object_Minimum_Diversification,w_int,method='SLSQP',\
                   bounds=bound, constraints={'type': 'eq', 'fun': constraint_equal_weight}).x

array([0.62263235, 0.22641537, 0.15095228])

In [41]:
minimize(object_Equal_Risk,w_int,method='SLSQP',\
                   bounds=bound, constraints={'type': 'eq', 'fun': constraint_equal_weight}).x

array([0.57545887, 0.2548402 , 0.16970093])

In [50]:
u = [0.1,0.1,0.1]
zigma_v = [0.1,0.2,0.3]
cov = np.array([[0.01,0.004,0.006],[0.004,0.04,0.03],[0.006,0.03,0.09]])

In [51]:
minimize(object_MVO,w_int,method='SLSQP',\
                   bounds=bound, constraints={'type': 'eq', 'fun': constraint_equal_weight}).x

array([8.57316082e-01, 1.42683918e-01, 1.27834670e-17])

In [52]:
minimize(object_Minimum_Variance,w_int,method='SLSQP',\
                   bounds=bound, constraints={'type': 'eq', 'fun': constraint_equal_weight}).x

array([0.85714286, 0.14285714, 0.        ])